.github/workflows/pr-commit-check.yml

fix: 커밋 workflow 수정 #3

---

src/App.tsx
src/components/common/Button.tsx
src/main.tsx
src/pages/Main.tsx
src/pages/SignIn.tsx
src/pages/SignUp.tsx

[Merge/design_로그인페이지_#6] design: 로그인레이아웃 #6

---

src/App.tsx
src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx

프로젝트 상세페이지에서 이동한 미팅룸 퍼블리싱했습니다
- #33

<merge/design_프로젝트상세-미팅룸_#33> design: 프로젝트상세-미팅룸 #33

---

src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/components/MeetingRoom/MeetingRoomMessage.tsx

<merge/refactor_채팅창-컴포넌트-분리_#35>refactor: 채팅창컴포넌트분리 #35

---

src/components/Admin/DashBoard.tsx
src/components/ProjectRoom/ProjectListBox.tsx

프로젝트 목록에 있는 프로젝트 박스에 태그 디자인추가 했습니다.
관리자 대시보드 뒷 배경 추가했습니다
#39

design: 프로젝트 태그 디자인/관리자 페이지 배경 수정 #39

---

src/assets/icons/sideCheckIcon.svg
src/components/ProjectRoom/ProjectListBox.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/layout/Layout.tsx
src/components/layout/ManagerCheckBox.tsx
src/components/layout/Sidebar.tsx
src/index.css
src/pages/ProjectRoom/ProjectRoom.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx

- 프로젝트룸 페이지, 프로젝트 상세페이지 디자인 수정
- 사이드바 담당자 부분 추가 및 디자인 수정
- 업무 박스 디자인 수정
#44

Design: 프로젝트 상세페이지 디자인 수정 #44

---

src/components/Admin/Account/Account.tsx
src/components/Admin/Project/Project.tsx

계정관리 페이지도 프로젝트 관리페이지와 마찬가지로
활성/비활성 구분 url이 아닌 컴포넌트로 처리했습니다
- #58

<merge/fix_계정관리페이지수정_#58>fix: 활성비활성구분수정 #58

---

src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/modals/CreateProjectModal.tsx
src/components/modals/CreateTaskModal.tsx
src/components/modals/UpdateTaskModal.tsx

1. 업무 생성, 편집 모달 퍼블리싱했습니다
2. 컴포넌트 업무모달, 프로젝트 모달에서 함께 쓰려면 제목 props로 내려야하는데 송원님 작업 중이셔서 일단 그대로두었습니다
3. 업무 편집시에는 컴포넌트로 현재 데이터 props로 내려야하는데 이부분도 일단 작업 중이셔서 그대로두었습니다
#61

<merge/design_업무생성편집-모달_#61>design: 업무생성편집-모달_#61

---

package.json
src/assets/animations/loading_note.json
src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/components/NoteList/DayNoteList.tsx
src/components/NoteList/NoteListBox.tsx
src/components/modals/CreateAINoteModal.tsx
src/components/modals/CreateNotePeriodModal.tsx
src/components/modals/NoteDetailModal.tsx
src/components/modals/NoteListModal.tsx

- 회의록 목록 모달, 기간 설정 모달, 회의록 초안 모달(로딩처리), 회의록 불러오기 모달 퍼블리싱했습니다
#63

<Merge/design_회의록-모달_#63>design: 회의록모달 #63

---

src/components/ProjectRoom/ProjectListBox.tsx
src/components/ProjectRoom/ProjectProgressBar.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/modals/CreateTaskModal.tsx
src/components/modals/EditProjectModal.tsx
src/components/modals/UpdateTaskModal.tsx
src/index.css
src/pages/ProjectRoom/ProjectRoom.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx

- 프로젝트 박스 디자인 수정사항 적용
- 프로젝트 상세페이지 커스텀스크롤 적용하여 전체 업무 박스 내에서만 스크롤 적용
- 업무 생성 모달에서 해당 값들 입력 시 화면을 벗어나 움직이지 않는 문제 해결 -> 스크롤 적용
- 진행 상태에 따른 버튼 변경 사항들 적용

Fixfeat 각 페이지별 세부조정 및 추가 #73

---

src/components/MainPage/Calendar.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/layout/Sidebar.tsx
src/constants/status.ts
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/types/projectDetailList.d.ts
src/utils/api/getProjectDetail.ts

- 프로젝트 상세페이지 안에 api로 받은 mock데이터를 설정했습니다. 
- 각 프로젝트 상세페이지로 들어가면 해당 프로젝트의 업무가 분류됩니다.!
- api이슈때문에 현재 전체업무 부분만 개발이 완료된 상황입니다!
#71

Feat: 프로젝트 상세 데이터 적용 #71

---

src/components/EditProjectModal/DateTimeSelect.tsx
src/components/EditProjectModal/SelectMember.tsx
src/components/EditProjectModal/WriteProjectName.tsx
src/components/MainPage/TodaySchedule.tsx
src/components/modals/EditProjectModal.tsx
src/types/date.d.ts
src/types/member.d.ts
src/types/project.d.ts
src/utils/api/createProject.ts

- 프로젝트 생성 기능 추가했습니다.
- 우선 임시 서버에 "/projects" 부분에 post 요청 보내게 했습니다
- post는 정상적으로 잘 되는데 노션에 적혀있는 api로 했을 때 추가한 프로젝트가 get으로 가져올 때 오류가 납니다.
- EditProjectModal에서 날짜, 시간 부분을 dayJs로 바꿨습니다.
- 프로젝트 명을 입력할 때 엔터키 안치고 입력만 한 상태에서 요청보내야 합니다 !
- DateTimeSelect 컴포넌트에 selectedDate와 setSelectedDate를 props로 필수로 받게 했습니다.
#79

feat: 프로젝트 생성 기능구현 #79

---

src/App.tsx
src/components/common/Button.tsx
src/components/layout/Header.tsx
src/pages/MainPage.tsx
src/pages/ProtectedRoute.tsx
src/pages/SignIn.tsx
src/pages/SignUpCompanyInfo.tsx
src/store/authStore.ts

- 로그인 시 localStorage에 저장
- 로그아웃 시 로컬스토리지 데이터 삭제
- 페이지 로그인 분기처리
#85

feat: 로그인 기능 임시구현 #85

---

src/pages/MyPage.tsx

<Merge/test-병합-테스트_#108>병합테스트

---

package.json
src/api/admin.ts
src/api/api.ts
src/api/auth.ts
src/api/project.ts
src/pages/MyPage.tsx
src/pages/ProjectRoom/ProjectRoom.tsx
src/pages/SignIn.tsx
vite.config.ts

로그인페이지에서 카카오로그인 버튼 누르면 임시 로그인 API 호출합니다. 
JSESSIONID 값을 .env파일에 넣어서 사용해주세요
- #110

<Merge/feat_api-연동-테스트2_#110>feat: 임시로그인api #110

---

package.json
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/layout/Layout.tsx
src/components/layout/ManagerCheckBox.tsx
src/components/layout/Sidebar.tsx
src/pages/MainPage.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/store/sideMemberStore.ts
src/types/projectDetailList.d.ts
src/types/task.d.ts
src/utils/api/getProjectDetail.ts

- 프로젝트 상세페이지 부분 담당자탭 구현했습니다
- 담당자 필터링 시 해당 담당자 업무 내용만 보이게 했습니다.
- 진행 중인 프로젝트 1번에 대해서만 구현이 완료되었습니다. 다른 데이터에는 아직 mock데이터가 추가되지 않았습니다.
- 전역상태관리로 체크박스 부분을 구현했습니다.
#111

Feat 프로젝트 상세 구현 #111

---

src/api/project.ts
src/api/task.ts
src/components/ProjectRoom/ProjectListBox.tsx
src/components/ProjectRoom/ProjectProgressBar.tsx
src/components/layout/Layout.tsx
src/components/layout/Sidebar.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/types/projectDetailList.d.ts

FEAT: 프로젝트 API 생성

---

src/api/admin.ts
src/api/api.ts
src/api/meetingroom.ts
src/api/project.ts
src/api/search.ts
src/pages/ProjectRoom/ProjectRoom.tsx
src/types/messages.d.ts
src/types/project.d.ts

아래 API 호출 함수 추가했습니다
- 채팅방
- 멤버 검색
- 프로젝트 리스트
- 프로젝트 생성
- 프로젝트 수정 정보(기존 정보) => 프로젝트 수정
- #116

<Merge/feat_api-호출_#116>feat: API함수추가 #116

---

src/api/project.ts
src/api/search.ts
src/components/modals/EditProjectModal.tsx
src/pages/ProjectRoom/ProjectRoom.tsx
src/types/project.d.ts

멤버, 프로젝트 검색 API 함수 추가했습니다
- #120

<Merge/feat_검색api함수-추가_#120>feat: 검색API함수 추가 #120

---

src/api/project.ts
src/api/search.ts
src/components/EditProjectModal/SelectCategory.tsx
src/components/EditProjectModal/SelectMember.tsx
src/components/EditProjectModal/WriteProjectName.tsx
src/components/MainPage/Calendar.tsx
src/components/ProjectRoom/ProjectListBox.tsx
src/components/modals/EditProjectModal.tsx
src/constants/calendarColors.ts
src/types/project.d.ts
src/utils/calendar/dragChange.ts
src/utils/progressType.ts

- 프로젝트 수정기능 구현
- 프로젝트 생성/수정 모달에서 유저 검색 구현
- 생성할 때 유저 검색에서 본인 포함시키면 안됩니다.
- 수정할 때 현재 api아직 수정이 안되어서 멤버id값을 가져오지 못합니다. 그래서 수정할 때 지금은 검색에서 본인을 포함시켜야 수정이 됩니다.
- 본인을 포함시키지 않으면 수정 버튼 누를 때 삭제됩니다 !!!
- 프로젝트 생성/수정 모달에서 인풋창에 오류가 있어서 현재 일단 input에서 값을 그냥 냅줘야 요청이 갑니다. 엔터 XXXX
- 카테고리 부분도 현재는 분야 부분만 선택해서 요청해야됩니다 ! 서브카테고리부분은 선택하시면 에러나요!
api수정되면 추가적으로 수정 진행하겠습니다~!
#125

Feat 프로젝트 수정api연결 #125

---

src/api/api.ts
src/components/EditProjectModal/WriteProjectName.tsx
src/components/MainPage/Calendar.tsx
src/components/modals/EditProjectModal.tsx
src/types/project.d.ts

- 프로젝트 생성 시 제목 빈칸으로 했을 때 빨간색으로 에러처리 했습니다.
- 추가적으로 카테고리분야도 처리를 해야하는데 api가 수정되면 바로 작업 진행하겠습니다.
#130

Fix 프로젝트 생성모달 제목/빈칸 #130

---

src/api/meetingroom.ts
src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/components/MeetingRoom/MeetingRoomMessage.tsx
src/components/modals/CreateAINoteModal.tsx
src/components/modals/CreateNotePeriodModal.tsx
src/components/modals/NoteListModal.tsx
src/pages/SignIn.tsx
src/types/messages.d.ts
src/types/projectDetailList.d.ts

1. 회의록 생성 API 적용했습니다
2. 현재 서버에서는 채팅 정보에서 sentAt이 null값이라, 회의록 생성이 안되는 상태입니다.
3. aws서버에서는 채팅 정보에 sentAt을 추가하셨다고 해서, aws서버에서 프로젝트 생성 적용되면 테스트해봐야 합니다
- #137

<Merge/feat_회의록-생성_#137>feat: 회의록생성 #137

---

src/api/admin.ts
src/api/api.ts
src/components/EditProjectModal/SelectCategory.tsx
src/components/MainPage/Calendar.tsx
src/components/ProjectRoom/ProjectListBox.tsx
src/components/modals/EditProjectModal.tsx
src/types/category.d.ts
src/types/project.d.ts
src/types/projectList.d.ts
src/utils/calendar/dragChange.ts
vite.config.ts

- 서버 주소 변경하고 설정 변경했습니다.
- 바뀐 api요청값에 따라서 프로젝트 생성/수정 모달 로직수정했습니다.
- 태그부분을 실데이터로 변경했습니다.
- SelectCategory 컴포넌트 부분이 더미데이터로 구현이 되어있어서 태그(실데이터)로 변경후 로직 수정했습니다.
- 프로젝트 수정할 때 참여인원에 생성한 사람 추가해야 정상적으로 수정됩니다. (백엔드에 수정 요청할 예정)
#139

Fix 서버주소 수정 #139

---

src/components/MainPage/Calendar.tsx
src/components/layout/Sidebar.tsx
src/utils/calendar/dragChange.ts

- 사이드바 담당자 필터링 오류 수정
- 캘린더 드래그 업데이트 오류 수정
#146 

fix: 사이드바 오류, 캘린더 드래그 함수 오류 수정 #146

---

src/pages/MainPage.tsx
src/pages/SignIn.tsx
src/utils/signInGoogle/getAccessToken.ts

- 구글 로그인 버튼 클릭 시 사용자정보 / access토큰 / id토큰을 불러오게 하였습니다
- 현재 백엔드 api 작업이 완료되지 않아, 로그인 버튼 클릭 시 로그인 화면에 머물게 하였습니다.

fix: 구글 로그인 구현(id/access 토큰)

---

src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/components/MeetingRoom/MeetingRoomMessage.tsx
src/components/modals/CreateAINoteModal.tsx
src/pages/SignIn.tsx

1. AI 회의록 생성됩니다. (조회, 수정, 저장은 API 나오면 추후 작업 필요)
2. 채팅방에 보낸시간 표시됩니다
3. 현재 메시지가 이전 이전메시지와 보낸 날짜가 달라졌을 시, 현재 메시지의 날짜를 띄워, 날짜 구분해줍니다.  
4. 현재 채팅방 날짜 데이터가 한국시간으로 넘어오지 않아 백엔드에 한국시간으로 변경 부탁드린 상태입니다. 
- #149

<Merge/feat_회의록-생성-테스트_#149>Feat 회의록 생성 테스트 #149

---

src/api/project.ts
src/api/search.ts
src/components/EditProjectModal/SelectCategory.tsx
src/components/EditProjectModal/SelectMember.tsx
src/components/ProjectRoom/ProjectListBox.tsx
src/components/modals/ConfirmModal.tsx
src/components/modals/EditProjectModal.tsx
src/pages/SignIn.tsx
src/types/member.d.ts
src/types/projectList.d.ts

- 프로젝트 나가기 / 삭제 구현했습니다!
- 생성자 일 경우 삭제버튼, 참여자일 경우 나가기 버튼으로 구현했습니다.
- ConfirmModal 쪽 조금 수정했는데 한번 확인만 해주세요
- 프로젝트 수정버튼 클릭시 모달에서 참여인원 표시했습니다
- 참여인원에서 생성자를 제거하고 수정요청보내면 오류납니다 추후에 수정예정입니다.
- 검색했을 때 멤버 데이터 타입과 멤버 선택했을 때 가져가는 데이터 타입이 살짝 달라서 수정했습니다
- 임시로 1번 2번 3번 로그인 버튼을 로그인페이지에 생성했습니다. 추후에 삭제예정입니다 ~~!
#148

Feat 프로젝트 나가기/삭제 구현 #148

---

src/api/meetingroom.ts
src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/components/NoteList/DayNoteList.tsx
src/components/NoteList/NoteListBox.tsx
src/components/modals/CreateAINoteModal.tsx
src/components/modals/CreateNotePeriodModal.tsx
src/components/modals/NoteDetailModal.tsx
src/components/modals/NoteListModal.tsx
src/types/messages.d.ts
src/utils/aiNote/dateUtils.ts

-회의록 생성, 등록, 수정, 조회 구현했습니다. 
-API 상으로 회의록 생성시에는 자동 등록되어서, 취소 버튼 누르면 삭제, 수정사항 있을 시 등록 버튼 누르면 등록(수정)되게 구현했습니다. 
-.env 폴더에 API_URL 끝에 / 빠져야 다른 api가 작동해서 / 빼고 웹소켓 연결 설정에 / 추가했습니다
- #155

<Merge/feat_회의록-추가-기능-구현_#155>feat: 회의록 추가구현 #155

---

src/api/project.ts
src/components/EditProjectModal/SelectCategory.tsx
src/components/EditProjectModal/SelectMember.tsx
src/components/MainPage/Calendar.tsx
src/components/ProjectRoom/ProjectListBox.tsx
src/components/modals/EditProjectModal.tsx
src/types/member.d.ts
src/utils/calendar/dragChange.ts

- 프로젝트 수정 권한이 주어집니다. 프로젝트 생성자만 수정버튼이 뜨도록 했습니다. 참여자는 수정 X
- 프로젝트 생성 또는 수정할 때 분야, 상세항목(1가지 이상) 선택 안하면 오류처리 했습니다. 다음페이지로 안넘어가게 됩니다. 또한 현재 날짜보다 과거로 설정할 경우 에러메시지 alert창으로 보여주게 했습니다.
- 프로젝트 생성 시 멤버 검색에서 본인(로그인한 사람)을 클릭 시 "프로젝트 생성자는 자동으로 참여인원에 포함됩니다" 멘트와 함께 선택이 안되게 했습니다.
- 프로젝트 수정 시 참여인원 프로필에 프로젝트 생성자를 클릭 할 경우 프로젝트 생성자는 참여인원에서 제거할 수 없습니다 멘트와 함께 삭제 불가능하게 했습니다.
- 캘린더에 본인이 참여자로 있는 프로젝트 기간을 수정 시 프로젝트 생성자만 수정이 가능합니다 멘트와 함께 수정 불가능하도록 했습니다.
- 혹여나 버그를 발견하게 되면 말씀해주세요 ~~!
#159

Feat 프로젝트 수정권한 처리 #159

---

src/components/EditProjectModal/SelectMember.tsx
src/components/modals/CreateTaskModal.tsx
src/types/member.d.ts
src/types/project.d.ts

- 업무 생성 시 담당자 지정이 되지 않는 버그 해결 및 그에 따른 타입 수정

Bug 업무담당자 미배정 오류 #165

---

src/api/api.ts
src/api/auth.ts
src/components/layout/Header.tsx
src/components/layout/Sidebar.tsx
src/pages/SignIn.tsx
src/pages/SignUpCompanyInfo.tsx
src/store/authStore.ts
src/types/social.d.ts

Feat 구글 로그인 테스트 #170

---

src/api/api.ts
src/api/auth.ts
src/components/ProjectRoom/ProjectListBox.tsx
src/components/layout/Header.tsx
src/components/layout/Layout.tsx
src/pages/MainPage.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/pages/ProtectedRoute.tsx
src/pages/SignIn.tsx
src/pages/SignUpCompanyInfo.tsx
src/store/authStore.ts

bug: 구글 로그인 버그 수정

---

src/App.tsx
src/components/MeetingRoom/MeetingRoomChatBox.tsx

웹소켓 연결시 토큰 추가해 연결하도록 수정했습니다
채팅 내용 잘 보내지는지, 제가 보낸 채팅 보이시는지만 확인 부탁드려요!
웹소켓 연결 알람에도 쓰여서 추후 zustand에서 전역적으로 연결하도록 수정할 에정입니다
-#172

<Merge/feat_로그인후-api-테스트_#172>feat: 웹소켓토큰인증 #172

---

src/hooks/useGoogleLogin.ts
src/pages/SignIn.tsx

- 구글 로그인 커스텀 훅을 따로 만들었습니다.
- signup 컴포넌트에서 커스텀 훅 적용하여 코드를 정리하였습니다.

Fix 구글 로그인 커스텀 훅 및 signin 컴포넌트 정리 #181

---

src/components/ProjectRoom/ProjectListBox.tsx
src/components/common/AlertModal.tsx

- alert 모달 확인, 취소 버튼 색상 서로 바꿨습니다
- #187

<Merge/design_alertmodal-버튼-생상-수정_#187>design: 알럿모달버튼색상수정 #187

---

src/api/api.ts
src/api/task.ts
src/components/MainPage/Calendar.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/modals/CreateTaskModal.tsx
src/constants/calendarColors.ts
src/styles/Calandar.css
src/types/task.d.ts
src/utils/calendar/dragChangeTask.ts

- 메인 페이지 - 캘린더 내 개인업무 데이터 연결했습니다.
- 풀캘린더 내 프로젝트/개인업무 버튼이 화면 초기 시 활성화가 되지 않습니다. (도저히 모르겠음)

feat: 캘린더 개인업무 연결

---

src/api/myPage.ts
src/components/MainPage/TodaySchedule.tsx
src/pages/MyPage.tsx

- 마이페이지 데이터 바인딩했습니다.
- 마이페이지에 이미지 변경하는 부분 수정했습니다 이미지 미리보기는 URL.createObjectURL으로 변경했습니다.
- 메인페이지 시계부분 1초마다 재랜더링 되는 것을 최적화했습니다.
- 마이페이지 로딩 중 스켈레톤 ui 적용했습니다.
#177

Feat 마이페이지 기능 구현 / 메인페이지 시계 최적화 #177

---

src/components/MainPage/ScheduleBox.tsx

- 1시간 이상은 00시 00분
- 1시간 미만은 00분
- 1분 미만은 00초로 남은 시간 수정

fix: 남은 시간 수정

---

src/App.tsx
src/components/MeetingRoom/MeetingRoomMessage.tsx
src/components/layout/Header.tsx
src/components/modals/NoteListModal.tsx
src/store/useWebSocketStore.ts

1. 2가지 버전 미팅룸에서 채팅 시, 해당 미팅룸에서 하는 채팅 알람은 UI필터링, API상 읽음처리되도록 했습니다. 
2. 미팅룸 긴 글 채팅 시 화면밖으로 벗어나는 문제 해결했습니다. 
3. 미팅룸 상대방 프로필 보더 추가했습니다. 
4. 회의록 없을 시, '아직 등록된 회의록이 없습니다' 문구 뜨도록 수정했습니다
- #203

<Merge/feat_미팅룸에서-알람-막기_#203>Feat 미팅룸에서 알람 막기 #203

---

src/components/Admin/Project/AdminProject.tsx
src/hooks/useGoogleLogin.ts
src/pages/SignIn.tsx

- 로그인 할 때 로딩창 추가했습니다
- 관리자 활성프로젝트 페이지 삭제버튼 제거했습니다.
- 로딩창 사진은 아까 줌에서 보여드린거로 진행했습니다.
#206

Fix 3차qa 로그인/관리자페이지 수정 #206

---

src/api/adminCategory.ts
src/components/Admin/Account/AdminAccount.tsx
src/components/Admin/Account/AdminAccountList.tsx
src/components/Admin/Project/AdminProject.tsx
src/components/Admin/Project/AdminProjectList.tsx
src/components/Admin/Tag/AdminTag.tsx
src/components/Admin/Tag/AdminTagAdd.tsx
src/components/Admin/Tag/AdminTagList.tsx
src/types/admin.d.ts

- 관리자 페이지 계정부분 다중 삭제 기능 추가
- 다중 삭제 시 삭제 멘트 변경
- 계정 수정 이름만 가능하도록 변경
- 카테고리 부분 로직 수정
#210

Fix 관리자페이지 수정 #210

---

src/components/MainPage/Calendar.tsx
src/components/MainPage/TodaySchedule.tsx
src/components/Task/TaskList.tsx
src/components/layout/Header.tsx
src/components/modals/CreateTaskModal.tsx
src/pages/MainPage.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx

- 헤더 알림 표시 색상 변경했습니다.
- 업무리스트 뒷 배경 세부사항 수정했습니다.
- 캘린더 이동 시 오늘의 업무에 바로 적용되도록 했습니다.

Fix 3차qa 메인페이지 업무관련 #204

---

src/api/api.ts

- 엑세스토큰 만료 시 리프레쉬 토큰을 이용해서 로그인을 유지하도록 했습니다.

fix: 리프레쉬 토큰을 이용한 로그인 유지

---

src/api/myPage.ts
src/components/Admin/Account/AdminAccount.tsx
src/components/EditProjectModal/DateTimeSelect.tsx
src/components/EditProjectModal/WriteProjectName.tsx
src/components/layout/AuthLayout.tsx
src/components/modals/EditProjectModal.tsx
src/components/modals/SimpleAlertModal.tsx
src/pages/MyPage.tsx
src/pages/ProjectRoom/ProjectRoom.tsx
src/pages/SignIn.tsx

- 마이페이지 수정 기능 구현
- 탈퇴 기능은 아직 api가 없어서 구현안했습니다.
- 1차 배포를 위해 안쓰는 코드 정리 했습니다
#213

Feat 마이페이지 수정기능 #213

---

src/components/MainPage/ScheduleBox.tsx
src/components/MainPage/TodaySchedule.tsx
src/components/modals/UpdateTaskModal.tsx
src/utils/signInGoogle/getAccessToken.ts

fix: 리다이렉트 uri 추가

---

src/components/MainPage/ScheduleBox.tsx

fix: 오류 수정

---

src/components/layout/Sidebar.tsx

- 프로젝트 상세페이지에서 새로고침 했을 때 사이드바 담당자 부분 전체 체크박스 풀리는 현상 수정했습니다.
#242
UI 변경이 있다면 스크린샷을 첨부해주세요

fix: 사이드바 새로고침 오류수정 #242

---

src/components/MainPage/TodaySchedule.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/types/task.d.ts

- 메인페이지 업무리스트에서 업무가 없을 경우 문구를 추가했습니다.
- 프로젝트 상세페이지 담당자에서 업무 수정 시 바로 변경이 안되는 문제 해결했습니다.

Feat 개인업무업을경우문구추가 #245

---

src/components/AlamModal/AlarmBox.tsx
src/components/Task/TaskList.tsx
src/components/layout/Header.tsx
src/components/modals/CreateNotePeriodModal.tsx
src/pages/ProjectRoom/ProjectRoom.tsx

-알람 모달에 호버 효과 추가했습니다 (호버시 보더 굵어지게 처리했습니다)
-헤더에 프로필 사진, 이름 추가했습니다
-프로젝트 디테일룸 전체 업무 진행상태 박스 height 짧게 보이는 부분이 어색해서 그라데이션으로 하단 배경색 투명도 추가했습니다
-프로젝트룸에서 알람모달 띄우면 프로젝트 삭제되는 문제 해결했습니다 (참여인원 제외된 프로젝트로도 이동하는 문제는 url 문제라 백엔드에 요청드렸습니다)
- #252

feat: 세부 수정 #252

---

src/components/ProjectRoom/ProjectListBox.tsx
src/components/common/AlertModal.tsx

<Merge/fix_버그-수정_#262>fix: z인덱스수정 #262

---

src/components/EditProjectModal/WordCloud.tsx
src/components/MainPage/ScheduleBox.tsx
src/pages/MyPage.tsx
src/pages/SignIn.tsx

- 캘린더박스에서 프로젝트 정보 불러오기 오류를 해결했습니다.
- 배포 시 워드클라우드의 미사용 매개변수에 대한 오류를 console.log 처리로 해결했습니다.
- 마이 페이지에서 파일 선택 취소 후 hover가 제대로 작동하지 않는 문제를 해결했습니다.
- 카카오 로그인 버튼을 주석처리했습니다.

Fix 배포 전 qa 수정 #264

---

src/components/ProjectRoom/ProjectListBox.tsx

fix: 2차배포 코드정리 #269

---

src/components/modals/CreateTaskModal.tsx

- 업무 생성 시 현재 시간이 11시 대일 경우 종료가 am에서 pm으로 변경되지 않는 문제 해결

bug: 업무 생성 시간 오류 해결

---

src/api/api.ts
src/pages/MainPage.tsx
src/pages/SignIn.tsx

- 리프레쉬 토큰으로 재로그인 시 일부 기능이 정상적으로 작동하지 않는 문제를 해결했습니다.

Bug 리프레쉬토큰 로그인 시 일부 기능 문제 발생 #280

---

src/pages/MyPage.tsx

fix: 이미지 변경 수정

---

src/pages/MyPage.tsx

fix: 마이페이지 오류 추가수정 #286

---

src/api/api.ts
src/components/MeetingRoom/MeetingRoomChatBox.tsx

진행중이 아닌 프로젝트의 미팅룸은 채팅 전송 불가하게 막고 placeholder와 toast로 문구 띄웠습니다. 
- #289

<Merge/fix_미팅룸-채팅-불가-처리_#289>Fix 미팅룸 채팅 불가 처리 #289

---

src/components/MeetingRoom/MeetingRoomChatBox.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx

- 사용자가 속하지 않거나, 유효하지 않은 프로젝트, 미팅룸 접근시 404페이지로 리다이렉트 처리했습니다
- #293

<Merge/fix_프로젝트룸-리다이렉트-수정_#293>fix: 프로젝트룸미팅룸리다이렉트수정 #293

---

src/api/auth.ts
src/api/category.ts
src/components/Admin/Tag/AdminTagChart.tsx
src/components/EditProjectModal/DateTimeSelect.tsx
src/components/EditProjectModal/SelectCategory.tsx
src/components/EditProjectModal/SelectMember.tsx
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/modals/CreateTaskModal.tsx
src/components/modals/EditProjectModal.tsx
src/components/modals/UpdateTaskModal.tsx
src/pages/ProjectRoom/ProjectRoom.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/pages/SignIn.tsx
src/store/authStore.ts
src/types/date.d.ts
src/types/task.d.ts

- 모달에서 사용하는 날짜 시간 AMPM 삭제했씁니다.
- 업무 생성/수정 날짜 선택 부분 수정했습니다
- dayjs로 변경 후 검증로직 다시 짰습니다.
- 마감일이 지난 프로젝트에서는 업무 생성/수정 못하도록 했습니다
- 로그인 인증유무를 따로 분리했습니다.
- 프로젝트 생성 모달에서 카테고리 api교체했습니다.
- 프로젝트 생성/수정 모달에서 기본이미지가 안나오는 오류 수정했습니다.
#278

Fix 로그인 오류수정 #278

---

src/api/admin.ts
src/api/adminCategory.ts
src/components/Admin/Account/AdminAccount.tsx
src/components/Admin/DashBoard.tsx
src/components/Admin/Project/AdminProject.tsx
src/components/Admin/Tag/AdminTag.tsx
src/components/Admin/Task/AdminTask.tsx
src/pages/MyPage.tsx

- 관리자 페이지 관리자인 계정만 들어갈 수 있도록 분기처리했습니다. 
- 관리자인 계정은 마이페이지 '관리자 페이지' 버튼 통해 관리자 페이지로 이동할 수 있습니다. 
- 관리자가 아닌 계정은 마이페이지에 '관리자 페이지' 버튼이 없으며, url 통해 이동하려고 할 시, 에러 페이지로 리다이렉트했습니다. 
- #295

<Merge/fix_관리자페이지-분기처리_#295>fix: 관리자페이지분기처리 #295

---

src/components/NoteList/NoteListBox.tsx
src/components/modals/CreateNotePeriodModal.tsx
src/components/modals/NoteDetailModal.tsx
src/utils/aiNote/dateUtils.ts

- 회의록 생성  시간 관련 ampm을 24시간 형식으로 수정했습니다
- #298

<Merge/fix_회의록-ampm-수정_#298>fix: 회의록 ampm 수정 #298

---

src/api/myPage.ts
src/pages/MyPage.tsx
src/pages/SignUpCompanyInfo.tsx
src/store/useWebSocketStore.ts

- 회원가입 후 정보 입력페이지, 마이페이지 중복되는 닉네임 입력 시 받는 에러에 따라 toast 띄우게 했습니다. 
- #301

<Merge/feat_닉네임-중복시-처리_#301>feat: 닉네임-중복시-처리_#301

---

src/api/auth.ts
src/store/authStore.ts

fix: 회원가입 후 메인 홈 오류 수정 #304

---

src/components/AlamModal/AlarmBox.tsx

알람 삭제되기 전에 페이지 넘어가서 삭제 안되는 부분 수정했습니다
- #307

<Merge/fix_알람-삭제-확인_#307>fix: 알람 삭제 수정 #307

---

src/pages/SignIn.tsx

fix: 로그인 페이지 디자인 수정

---

src/components/layout/Header.tsx

fix: 로그아웃 오류 수정 #313

---

package.json
src/api/task.ts
src/components/Task/TaskBox.tsx
src/components/Task/TaskList.tsx
src/components/common/LoadingLottie.tsx
src/pages/ProjectRoom/ProjectRoomDetail.tsx
src/utils/progressType.ts

- 업무 박스 드래그 기능 추가했습니다
- 전체업무에서 드래그 시 상태만 변경 됩니다.
- 담당자별 업무에서 드래그 시 담당자만 변경됩니다.
#311

Feat task drag기능 추가 #311

---

src/api/adminDetailTag.ts
src/api/adminSubCategory.ts
src/components/Admin/Tag/AdminCategoryBox.tsx
src/components/Admin/Tag/AdminDetailTagBox.tsx
src/components/Admin/Tag/AdminSubCategoryBox.tsx
src/components/Admin/Tag/AdminTag.tsx
src/components/Admin/Tag/AdminTagList.tsx

refactor 관리자 태그 리팩토링 #319

---

src/components/MainPage/TodaySchedule.tsx
src/components/layout/Header.tsx
src/components/modals/AlarmModal.tsx
src/index.css
src/pages/MainPage.tsx
src/styles/Calandar.css

메인페이지 및 헤더 모바일 반응형 디자인 적용
#323

Feat/메인페이지 모바일 디자인 추가/#323

---

src/components/ProjectRoom/ProjectListBox.tsx
src/components/modals/EditProjectModal.tsx
src/pages/ProjectRoom/ProjectRoom.tsx

프로젝트룸 페이지, 프로젝트 생성/수정 모달 모바일 반응형 디자인 적용
#327

feat: 프로젝트룸, 프로젝트 생성/수정 모달 반응형 디자인 #327
