- package.json
- src/App.tsx
- src/components/MainPage/ScheduleBox.tsx
- src/components/MainPage/TodaySchedule.tsx
- src/components/layout/Header.tsx
- src/components/layout/Layout.tsx
- src/components/layout/Sidebar.tsx
- src/pages/MainPage.tsx
사이드바와, 헤더부분 레이아웃으로 퍼블리싱 했습니다.
메인페이지에서 로그인 상태일 시 캘린더와 현재 업무 박스를 퍼블리싱 했습니다.
tailwind-merge, FullCalendar 라이브러리 설치했습니다.
#5
> design: 메인페이지 로그인상태, 레이아웃 디자인 #5

- package.json
- src/App.tsx
- src/components/common/Button.tsx
- src/layouts/AuthLayout.tsx
- src/pages/SignIn.tsx
- src/pages/SignUp.tsx
- src/pages/SignUpCompanyInfo.tsx
1. 회원가입, 회원가입 후 소속 입력 페이지 레이아웃 퍼블리싱했습니다
2. AuthLayout에 헤더 추가했습니다.
3. 헤더에서 로그인, 회원가입 클릭 시 로그인, 회원가입으로 이동하도록 경로 수정했습니다.
#8
> [merge/ design_회원가입레이아웃_#8] fix: AuthLayout헤더추가 #8

- package.json
- src/components/MainPage/Calendar.tsx
- src/components/MainPage/ScheduleBox.tsx
- src/components/MainPage/TodaySchedule.tsx
- src/pages/MainPage.tsx
- src/styles/Calandar.css
- 라이브러리 설치
1. dayjs 날짜 포맷팅
2. @fullcalendar/interaction 캘린더 드래그 기능 라이브러리
**캘린더 컴포넌트로 분리하였습니다**
캘린더 디자인 커스텀해서 변경했습니다.
캘린더 부분에 데이터 삽입했고 현재 드래그 기능까지 됩니다.
메인페이지 업무일정 부분 피그마에 맞게 수정했습니다.
피그마에서는 분까지 나와있는데 초 단위까지 화면에 보여주고 1초마다 업데이트 되도록 하였습니다
#25
> Feat: 캘린더 임시데이터 삽입, 드래그 기능, 커스텀/ 메인페이지 디자인 수정 #25

- .gitignore
- package.json
- src/App.tsx
- src/api/api.ts
- src/components/AlamModal/AlarmBox.tsx
- src/components/MainPage/Calendar.tsx
- src/components/MeetingRoom/MeetingRoomChatBox.tsx
- src/components/ProjectRoom/ProjectListBox.tsx
- src/components/layout/Header.tsx
- src/components/layout/Sidebar.tsx
- src/main.tsx
- src/pages/SignIn.tsx
- src/types/projectList.d.ts
- src/utils/api/getProjectList.ts
- src/utils/calendar/dragChange.ts
1. 웹사이트 url 수정
2. 캘린더 mock데이터 심기
- 임시 서버 구동을 위해 json-server를 설치하였습니다. (msw를 사용하려다가 이슈가 있어서 변경했습니다)
- 프로젝트의 리스트는 일단 /projects로 요청하면 받아옵니다. (기존 url ->  /project/list)
- 로컬 최상단 폴더에 db.json 파일을 생성 후에 mock데이터를 작성하시면 됩니다.
- axios 인스턴스를 임시로 생성했습니다 baseUrl => localhost:3000
- 백엔드 측에서 보내주신 Res데이터로 임시로 타입 설정, mock데이터 생성했습니다.
3. 캘린더 데이터 드래그 시 수정
- 드래그 하고 난 후에 서버에 업데이트 요청을 보내는 함수 구현
- 일정 길이 조절할 떄 위와 동일한 함수로 업데이트 요청합니다.
#42 
https://github.com/user-attachments/assets/56b40443-6169-44f2-a4dd-cd2a6babd5ca
> Feat: 캘린더 mock데이터 설정, url수정 #42

- package.json
- src/components/MainPage/Calendar.tsx
- src/components/ProjectRoom/ProjectListBox.tsx
- src/components/layout/Sidebar.tsx
- src/components/modals/CreateTaskModal.tsx
- src/components/modals/UpdateTaskModal.tsx
- src/index.css
- src/main.tsx
- src/pages/ProjectRoom/ProjectRoom.tsx
- src/pages/ProjectRoom/ProjectRoomDetail.tsx
- src/types/projectList.d.ts
- src/utils/api/getProjectDetail.ts
- db.json 파일에 mock데이터를 수정해서 다시 설정했습니다.
- 캘린더 부분 로직 수정했습니다.
- 프로젝트룸 페이지에 mock데이터를 받아와서 나열했습니다. 각 탭에 따라 필터링해서 적용했습니다.
- 프로젝트 상세페이지에서 프로젝트 상세데이터를 가져오기까지 구현했습니다.
- create, update task modal에서 파일경로 오류나는거 수정했습니다.
- tanstack query devtools 설치했습니다 npm install 해주세요 !
#65
> feat: 프로젝트 리스트 데이터 적용 #65

- src/components/MainPage/Calendar.tsx
- src/components/ProjectRoom/ProjectListBox.tsx
- src/components/ProjectRoom/ProjectProgressBar.tsx
- src/components/Task/TaskBox.tsx
- src/components/common/ParticipantIcon.tsx
- src/components/modals/EditProjectModal.tsx
- src/constants/calendarColors.ts
- src/types/button.d.ts
- src/types/projectList.d.ts
- src/utils/randomColor.ts
- 수정된 프로젝트 리스트 mock데이터를 기반으로 메인, 프로젝트룸 페이지 수정했습니다.
- 프로젝트룸 페이지에 참여인원 이미지 적용했고 아이콘 크기 기존 30px -> 35px로 변경했습니다.
- 진행률에 맞게 데이터를 설정했습니다.
- 태그 부분에 데이터를 반영해서 적용했습니다.
- 프로젝트 생성할 때 캘린더에 표시될 프로젝트 랜덤색상 값 생성했습니다. 
#89
> fix: 프로젝트리스트 수정데이터 반영 #89

- .gitignore
- src/components/MainPage/Calendar.tsx
- 캘린더 데이터 값 넘칠 때 높이 늘어나게 하지 않고 + n개 이런 형식으로 수정했습니다.
- 캘린더안의 데이터 클릭시 해당 상세프로젝트로 이동하게 했습니다.
#93
> fix: 1차 QA 캘린더 높이조절 #93

- src/api/admin.ts
- src/components/Admin/Chart.tsx
- src/components/Admin/DashBoard.tsx
- src/components/MeetingRoom/MeetingRoomChatBox.tsx
- src/components/MeetingRoom/MeetingRoomMessage.tsx
- src/types/admin.d.ts
- 관리자 대시보드 그래프 부분 데이터 연결
- 그래프 높이값 조정
- 총 구독회원 수 -> 총 회원 수로 변경
#132
> feat: admin페이지 대시보드 데이터 연결 #132

- src/api/admin.ts
- src/components/Admin/Account/AdminAccount.tsx
- src/components/Admin/Account/AdminAccountList.tsx
- src/types/admin.d.ts
- 관리자 계정관리 페이지 부분 기능 구현
- 관리자 계정 수정기능 추가 -> 날짜 수정 XXX  이름, 소속, 프로필이미지 수정가능
- 관리자 계정관리 부분 오른쪽 구독 버튼 삭제 -> 수정버튼 추가, 하단에 수정 취소버튼 추가
- 체크박스 클릭 후 삭제 가능 -> 다중 선택 XXX api상으로 하나씩만 보내게 되어있음
- 추후에 검색기능 추가 개발 필요
#136
> Feat 관리자 계정관리 기능구현 #136

- src/api/admin.ts
- src/components/Admin/Task/AdminTask.tsx
- src/components/Admin/Task/AdminTaskList.tsx
- src/components/Task/TaskList.tsx
- src/components/modals/UpdateTaskModal.tsx
- src/types/task.d.ts
- 담당자별 업무리스트에서 배정된 업무가 없더라도 기본 백그라운드가 보이게 변경하였습니다.
- 관리자 업무 페이지에서 업무 리스트 api 호출로 데이터를 연결하였습니다.
- 업무 수정 api 연결하여 기능 구현하였습니다. (업무명, 진행상태만 변경 가능하도록 변경)
- 비활성 업무 리스트를 받아와서 활성 / 비활성 탭으로 구분하였습니다.
> feat: 관리자 업무 데이터 연결 및 수정

- src/components/Admin/Account/AdminAccount.tsx
- src/components/Admin/Project/AdminProject.tsx
- src/components/EditProjectModal/SelectMember.tsx
- src/components/MainPage/Calendar.tsx
- src/components/ProjectRoom/ProjectListBox.tsx
- src/components/common/AlertModal.tsx
- src/components/modals/ConfirmModal.tsx
- src/components/modals/CreateTaskModal.tsx
- src/pages/SignUpCompanyInfo.tsx
1. 사용자가 봐야하는 alert창은 AlarmModal 컴포넌트로 모달처리했습니다
2. 관리자 프로젝트, 계정 삭제 시 체크박스 선택 안하면 선택하라는 경고 문구, 선택시, '정말로 삭제하시겠습니까?' 모달에서 확인 버튼 누르면 삭제되도록 수정했습니다. 
- #185
> <Merge/fix_alert-모달로-변경_#185> fix: alert을 모달로 변경 #185

- src/api/admin.ts
- src/components/Admin/Task/AdminTask.tsx
- src/components/Admin/Task/AdminTaskList.tsx
- src/components/EditProjectModal/SelectMember.tsx
- src/components/Task/TaskBox.tsx
- src/components/Task/TaskList.tsx
- src/components/layout/ManagerCheckBox.tsx
- src/components/layout/Sidebar.tsx
- src/components/modals/AlertModal.tsx
- src/components/modals/ConfirmModal.tsx
- src/components/modals/CreateTaskModal.tsx
- src/pages/ProjectRoom/ProjectRoomDetail.tsx
- src/types/projectDetailList.d.ts
- src/types/projectList.d.ts
- src/types/task.d.ts
- 관리자 업무 페이지 - 업무 삭제 기능을 구현했습니다.
- 관리자 업무 페이지 - 기능이 사라진 버튼들을 정리했습니다.
- 프로젝트 상세 페이지 - 기존 발생한 타입 오류를 해결하고 타입을 일부 정리했습니다.
- 프로젝트 상세 페이지 - 사이드바 담당자 체크박스를 글자순으로 정렬했습니다.
- 프로젝트 상세 페이지 - 담당이 아닌 업무는 편집이 불가하도록 설정했습니다.
- 프로젝트 상세 페이지 - 담당 업무박스는 hover 시 디자인을 추가하여 가독성을 개선했습니다.
- 프로젝트 상세 페이지 - 업무 생성 및 편집 시 지정 가능한 담당자를 프로젝트 참여인원에 한정했습니다.
진행 중인 내용
- 메인 페이지 내 업무 관련 사항들
- 관리자 업무 페이지 내 업무 검색 기능
> Feat 관리자페이지 업무 삭제 메인페이지 업무 기능 #183

- src/api/admin.ts
- src/api/adminCategory.ts
- src/api/adminDetailTag.ts
- src/api/adminSubCategory.ts
- src/components/Admin/Button/AdminDeleteBtn.tsx
- src/components/Admin/Button/AdminEditCancelBtn.tsx
- src/components/Admin/Tag/AdminTag.tsx
- src/components/Admin/Tag/AdminTagAdd.tsx
- src/components/Admin/Tag/AdminTagBox.tsx
- src/components/Admin/Tag/AdminTagList.tsx
- src/components/EditProjectModal/SelectCategory.tsx
- 관리자페이지 태그부분 기능구현했습니다.
- 현재 세부항목(서브카테고리) 부분에서 이슈가 많아서 백엔드분들께 확인요청부탁드렸습니다.
- 서브카테고리 이슈사항
1. 삭제가 되는 것이 있고 안되는 것이 있음
2. 새로 생성시 response로 500에러가 뜨지만 추가는 정상적으로 됨 (새로고침 해야됩니다)
3. 수정 시 response로 정상적으로 응답값이 오는데 데이터베이스에 수정된 서브카테고리 반영이 안됩니다.
- 분야 선택 -> 세부항목(서브카테고리) 선택 -> 상세항목 순으로 클릭해야 항목들이 보입니다.
- 각 항목 수정/추가할 때 빈 문자열일 경우 경고창 띄웁니다.
- admin 태그 부분과 관련된 api가 너무 많아서 분야, 세부항목, 상세항목 형식으로 파일 분리했습니다.
#179
> Feat 관리자페이지 태그부분 구현 #179

- src/components/MainPage/Calendar.tsx
- src/components/MainPage/ScheduleBox.tsx
- src/components/MainPage/TodaySchedule.tsx
- src/components/Task/TaskBox.tsx
- src/components/Task/TaskList.tsx
- src/components/modals/ConfirmModal.tsx
- src/components/modals/UpdateTaskModal.tsx
- src/styles/Calandar.css
- 메인페이지 프로젝트/개인업무 버튼 클릭 시 활성/비활성화 스타일 적용했습니다.
- 메인페이지 개인업무 리스트에 데이터 적용했습니다 (추가 수정 중)
- 업무박스에서 기간 오류 및 편집모달에서의 오류 해결했습니다.
> Fix 캘린더 프로젝트개인업무 버튼 #196

- src/components/EditProjectModal/DateTimeSelect.tsx
- src/components/modals/EditProjectModal.tsx
- src/types/project.d.ts
- 프로젝트 생성 시 모달에서 날짜 선택 제한했습니다.
- 시작 날짜는 하루 전부터 가능하고 종료 날짜는 시작날짜보다 뒤로 설정하도록 경고창 설정했습니다.
- 
#198
> Fix 프로젝트 생성모달 날짜제한 수정 #198

- src/api/search.ts
- src/components/Admin/Task/AdminTask.tsx
- src/hooks/useGoogleLogin.ts
- src/types/task.d.ts
- 관리자 페이지 - 업무 검색기능 구현했습니다
-> 업무 데이터에는 활성 비활성을 구분하는 키 값이 없기 때문에 필터로 검색 기능 구현했습니다
- 구글 로그인 리다이렉트_URI 추가했습니다
> Feat 관리자페이지 업무검색 #219

- src/api/api.ts
- src/api/project.ts
- src/components/EditProjectModal/SelectMember.tsx
- src/components/MainPage/TodaySchedule.tsx
- src/components/Task/TaskBox.tsx
- src/components/Task/TaskList.tsx
- src/components/modals/CreateTaskModal.tsx
- src/components/modals/UpdateTaskModal.tsx
- src/pages/ProjectRoom/ProjectRoomDetail.tsx
- src/types/project.d.ts
- src/types/projectDetailList.d.ts
- src/types/task.d.ts
- 리프레쉬 토큰으로 로그인 시 유저 정보를 불러오지 못하는 버그를 수정했습니다.
- 업무편집생성모달 - 시작/종료일을 프로젝트 시작/종료일로 설정했습니다.
- 프로젝트 기간을 벗어나면 모달이 열리면서 기간 설정에 제한을 주었습니다.
- 프로젝트 참여 인원임에도 참여인원이 아니라는 모달이 뜨는 버그를 해결했습니다.
- 업무 편집 시 업무박스에 바로 렌더링 되지 않는 부분을 수정했습니다.
> Fix 1차 배포 qa 업무생성편집모달 #240

- src/api/admin.ts
- src/components/Admin/Account/AdminAccount.tsx
- src/components/Admin/Account/AdminAccountList.tsx
- src/components/Admin/Project/AdminProject.tsx
- src/components/Admin/Project/AdminProjectList.tsx
- src/components/Admin/Task/AdminTask.tsx
- 관리자페이지 계정/프로젝트/업무 부분 복구기능 구현했습니다.
- 관리자 계정/프로젝트 부분 전체선택  기능 추가했습니다.
- 계정, 프로젝트 삭제 로직 수정했습니다.
#241
> Feat 관리자 복구기능 구현 #241

- src/components/AlamModal/AlarmBox.tsx
- src/components/modals/CreateNotePeriodModal.tsx
- src/pages/ProjectRoom/ProjectRoom.tsx
- src/pages/ProjectRoom/ProjectRoomDetail.tsx
- src/store/useWebSocketStore.ts
- src/types/projectList.d.ts
* 프로젝트룸에서 이동하는 미팅룸에 배경 추가했습니다.
* AI회의록 제목 작성 안하면 알람 모달 띄우고 다음 모달로 넘어가지 않도록 막았습니다.
* AI회의록에서 설정한 시간에 띄워줄 내용이 없으면 ‘ 해당 시간에 채팅 기록이 없습니다’ 기본으로 띄우기
=> 이렇게 띄우게 되면 회의록 생성이 안된 것이기 때문에 reportId가 없어서 회의록 등록이 안됩니다. (기록이 없다고 뜨더라도 사용자가 수정해 등록하고자 할 수 있음)
=> 따라서 회의록 생성이 안되면 시간 설정해달라는 모달 띄우고 다음 모달로 넘어가지 않도록 막았습니다. 
* 알람 모달에서 메시지랑 프로젝트, 업무명 각각 1px씩 키웠습니다.
* 프로젝트 참여인원 수정해 사용자가 프로젝트에서 빠질 시, 해당 프로젝트에 대해 남아있는 알람 클릭하면 해당 프로젝트 룸이 아닌 404페이지로 이동하도록 수정했습니다.  
- #239
> <Merge/fix_1차배포qa-미팅룸회의록알람-수정_#239>fix: 1차배포qa수정 #239

- src/api/myPage.ts
- src/components/Admin/Account/AdminAccountList.tsx
- src/pages/MyPage.tsx
- src/pages/SignUpCompanyInfo.tsx
- src/types/admin.d.ts
- 마이페이지 기본이미지 적용 오류 수정했습니다.
- 사용자가 이름과 소속만 변경한다면 이미지 파일은 formdata에 추가되지 않습니다.
- 사용자가 기본이미지로 변경한다면 이미지 파일은 빈 파일형식으로 보냅니다.
- 회원 등록하기 부분에서 이메일제거 했습니다.
- 회원 등록하기/마이페이지 에서 label 부분 폰트 크기 조정했습니다
- 관리자 계정 수정 요청값 newName -> name으로 변경했습니다.
#247
> Fix 마이페이지 기본이미지 변경오류 #247

- src/components/MeetingRoom/MeetingRoomChatBox.tsx
- src/components/ProjectRoom/ProjectListBox.tsx
- src/store/useWebSocketStore.ts
미팅룸 웹소켓 연결을 컴포넌트에서 개별적으로 관리하고 있었음.
미팅룸의 타입이 변경될 때(예: meeting-room/3 → project-room/3?category=meeting) 새로고침하지 않으면 WebSocket 구독이 안 되는 문제 발생.
알람 웹소켓(전역 상태로 관리됨)과 충돌하여 채팅 웹소켓 구독이 정상적으로 되지 않는 현상이 있었음.
- 웹소켓 연결은 전역 연결을 함께 쓰고, 미팅룸 컴포넌트에서는 채팅 웹소켓 구독만 하도록 수정하여 
다른 미팅룸 타입으로 이동했을 때 웹소켓 연결이 안되는 문제 해결했습니다.
- #257
> <Merge/feat_미팅룸-웹소켓-구독-관련_#257>feat:미팅룸웹소켓전역변경 #257

- src/components/Admin/Tag/AdminTag.tsx
- src/components/Admin/Tag/AdminTagChart.tsx
- src/components/Admin/Tag/TagCountBox.tsx
- src/components/layout/Header.tsx
- src/pages/ProtectedRoute.tsx
- src/store/authStore.ts
- 관리자 태그 데이터 그래프 구현했습니다.
- 총 분야, 세부항목, 상세항목 갯수 컴포넌트로 만들어서 표현했습니다.
- authStore에 오류가 있어서 수정했습니다.
- isAuthenticated 부분이 액세스토큰으로 구분을 해서 boolead값으로 변경했습니다.
- user부분 사용안해서 제거했습니다.
#259
> feat: 대그데이터 그래프 구현 #259

- src/components/ProjectRoom/ProjectListBox.tsx
- src/components/modals/EditProjectModal.tsx
- 프로젝트 생성 후 새로고침해야 리스트에 생성되는 버그 수정
- 모든 프로젝트 리스트에 미팅룸 버튼 추가
- 모달 z-index 추가
#263 
> fix: 프로젝트 리스트 버그 수정 #263
